# Generated by Django 3.1.5 on 2021-01-04 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=255, verbose_name='nama depan')),
                ('last_name', models.CharField(max_length=255, verbose_name='nama belakang')),
                ('nik', models.CharField(max_length=20, verbose_name='nomor induk kependudukan')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='biodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField(default=None, verbose_name='ttl')),
                ('gender', models.CharField(choices=[('F', 'Perempuan'), ('M', 'Pria')], max_length=300, verbose_name='gender')),
                ('adress', models.TextField(verbose_name='alamat')),
                ('contact', models.CharField(max_length=20, verbose_name='nomor telepon')),
                ('acc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.acc', verbose_name='Account')),
            ],
        ),
    ]
