# Generated by Django 3.1.5 on 2021-01-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='adress',
            field=models.TextField(blank=True, verbose_name='alamat'),
        ),
        migrations.AddField(
            model_name='acc',
            name='birth',
            field=models.DateField(blank=True, default=None, verbose_name='ttl'),
        ),
        migrations.AddField(
            model_name='acc',
            name='contact',
            field=models.CharField(blank=True, max_length=20, verbose_name='nomor telepon'),
        ),
        migrations.AddField(
            model_name='acc',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Perempuan'), ('M', 'Pria')], max_length=300, verbose_name='gender'),
        ),
        migrations.DeleteModel(
            name='biodata',
        ),
    ]
