# Generated by Django 3.1.5 on 2021-01-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210106_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='birth',
            field=models.DateField(default=None, null=True, verbose_name='ttl'),
        ),
    ]
