# Generated by Django 3.1.5 on 2021-01-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='umkm',
            name='descript',
            field=models.TextField(blank=True),
        ),
    ]
